### ISSUE TITLE
Singleplayer/LAN autokick

### ISSUE THREAD

**Issue by Puzolics** [henkelmax/mod-enforcer#1]
Bug:
- Loading a singleplayer world kicks yourself out.

Reproduction:
- Launch with Mod Enforcer installed, make a new world, wait about 4-8 seconds.

Log:
https://pastebin.com/vMMCf65K

Recreated with a fresh forge install, mod download, and directory:
https://streamable.com/cz2vjk

Versions:
- Minecraft 1.16.4
- Forge 35.0.2 and 35.0.18
- 1.0.0 going by the jar file name

Found this with 90 or so other mods installed, only around 3-4 of the mods I used even touch server packets and client data, Fast Furnace/Workbench and Recipe Buffers to name a couple. The rest are ye-ol' biomes, ores, world generation, etc. The problem still persists with Mod Enforcer installed all by itself with no other mods.

I know this mod is for dedicated servers but I'd like to use it for LAN worlds hosted over Hamachi. A friend drops in Optifine for shaders and refuses to remove it, breaking one mod modifying light levels, and nullifying another mod adding an item with dynamic lighting. It's not your issue my friend is stubborn, but your mod is perfect for this.

**Comment by henkelmax** [comment]
Thanks for reporting this issue. Let me know if it works for you.
