### ISSUE TITLE
Mod Whitelist

### ISSUE THREAD

**Issue by Yucareux** [henkelmax/mod-enforcer#2]
**Is your feature request related to a problem? Please describe.**
Is not a problem, I was thinking if there could be an option in which you can set the mods that are allowed by server, like, if someone wants to join the server, the player must have just the mods that are allowed by the server, making this a kind of anticheat for Forge.

**Describe the solution you'd like**
So, for this, there may be a whitelist with the MD5 (hashmaps) of the mods, so players can not bypass it. So, the mod gets the hashmaps of the mods on the server, so the user dont have to add them manually.

**Describe alternatives you've considered**
There is a mod that is actually outdated, and the developer has stated that he will not  work on the mod for a while, its name is WatchDog Anti Cheat for Forge, that was my only alternative.

**Additional context**
Also, the option to add manually more mods to the whitelist so, people with different mods can join the server without having them on the server itself.

**Comment by henkelmax** [comment]
This mod is not intended as some kind of anticheat. You can very easily trick the mod into thinking you have no other mods installed. It's just used as a kind of failsafe if someone forgot to update (or add) their mod on the client.
